#!/bin/sh

# Title:         my_setup CLI Tool
# Description:   my_setup CLI Tool for Bash/Zsh/Sh/Ksh
# Author:        Sunny Pun <sunnyppsp@gmail.com>

set -eu
VERSION="0.0.1"
SCRIPT_NAME=$(basename "$0")

# Set variables
TODO_NAME="todo.md"

# Keep readlinkf function
readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
todo_file="$script_dir/$TODO_NAME"
# For Debian APT remove line 7 to 38 and use the following line to
# define the script_dir
# script_dir="/usr/share/shellscript_template"

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/utils.sh"
    . "${script_dir}/lib/automata_definition.sh"
    . "${script_dir}/lib/installer_definition.sh"
    . "${script_dir}/lib/version_control_tools_definition.sh"
    . "${script_dir}/lib/cmd1_definition.sh"
    . "${script_dir}/lib/cmd2_definition.sh"
    . "${script_dir}/lib/create_definition.sh"
    # import only one of helpers file
    # . "${script_dir}/lib/shell_helpers.sh"
    # or
    # . "${script_dir}/lib/bash_helpers.sh"
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    cmd1)
        eval "$(getoptions parser_definition_cmd1 parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/cmd1.sh"
        fn_cmd1 "$@"
        ;;
    cmd2)
        eval "$(getoptions parser_definition_cmd2 parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/cmd2.sh"
        fn_cmd2 "$@"
        ;;
    text_example)
        # shellcheck disable=SC1091
        . "${script_dir}/src/text_example.sh"
        fn_text
        ;;
    create)
        eval "$(getoptions parser_definition_create parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/create.sh"
        fn_create "$@"
        ;;
    automata)
        eval "$(getoptions parser_definition_automata parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/automata.sh"
        fn_automata
        ;;
    installer)
        eval "$(getoptions parser_definition_installer parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/installer.sh"
        fn_installer
        ;;
    version_control_tools)
        eval "$(getoptions parser_definition_version_control_tools parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/version_control_tools.sh"
        fn_version_control_tools
        ;;
        
    # more lines
    --) ;; # no subcommand, arguments only
    esac
fi
